# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: SVm 기술 블로그
email: dev@insertcoin.me
description: > # this means to ignore newlines until "baseurl:"
  Recreate Mobile Video Culture.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://svm-dev.github.io/" # the base hostname & protocol for your site
twitter_username: hello_svm
github_username: StarshipVendingMachine

# comments
comments: true

# Build settings
markdown: kramdown
